pragma options "--bnd-inline-amnt 2";
pragma options "--bnd-inbits 2";

generator bit predicate(int n, bit[n] bits) {
    int choose = ??;
    if(choose == 0) {
        return bits[??];
    } else if(choose == 1) {
        return predicate(n, bits) ||
               predicate(n, bits);
    } else if (choose == 2){
        return predicate(n, bits) &&
               predicate(n, bits);
    } else {
        return !predicate(n, bits);
    }
}

bit program(int n, bit[n] bits){
    return predicate(n, bits);
}

@FromFile("inputs.txt")
harness void main(int n, bit[n] bits, bit out) {
    assert(program(n, bits) == out);
}

