ABC_SRCS +=  $(ABC)/src/bdd/cudd/cuddAPI.c \
	$(ABC)/src/bdd/cudd/cuddAddAbs.c \
	$(ABC)/src/bdd/cudd/cuddAddApply.c \
	$(ABC)/src/bdd/cudd/cuddAddFind.c \
	$(ABC)/src/bdd/cudd/cuddAddInv.c \
	$(ABC)/src/bdd/cudd/cuddAddIte.c \
	$(ABC)/src/bdd/cudd/cuddAddNeg.c \
	$(ABC)/src/bdd/cudd/cuddAddWalsh.c \
	$(ABC)/src/bdd/cudd/cuddAndAbs.c \
	$(ABC)/src/bdd/cudd/cuddAnneal.c \
	$(ABC)/src/bdd/cudd/cuddApa.c \
	$(ABC)/src/bdd/cudd/cuddApprox.c \
	$(ABC)/src/bdd/cudd/cuddBddAbs.c \
	$(ABC)/src/bdd/cudd/cuddBddCorr.c \
	$(ABC)/src/bdd/cudd/cuddBddIte.c \
	$(ABC)/src/bdd/cudd/cuddBridge.c \
	$(ABC)/src/bdd/cudd/cuddCache.c \
	$(ABC)/src/bdd/cudd/cuddCheck.c \
	$(ABC)/src/bdd/cudd/cuddClip.c \
	$(ABC)/src/bdd/cudd/cuddCof.c \
	$(ABC)/src/bdd/cudd/cuddCompose.c \
	$(ABC)/src/bdd/cudd/cuddDecomp.c \
	$(ABC)/src/bdd/cudd/cuddEssent.c \
	$(ABC)/src/bdd/cudd/cuddExact.c \
	$(ABC)/src/bdd/cudd/cuddExport.c \
	$(ABC)/src/bdd/cudd/cuddGenCof.c \
	$(ABC)/src/bdd/cudd/cuddGenetic.c \
	$(ABC)/src/bdd/cudd/cuddGroup.c \
	$(ABC)/src/bdd/cudd/cuddHarwell.c \
	$(ABC)/src/bdd/cudd/cuddInit.c \
	$(ABC)/src/bdd/cudd/cuddInteract.c \
	$(ABC)/src/bdd/cudd/cuddLCache.c \
	$(ABC)/src/bdd/cudd/cuddLevelQ.c \
	$(ABC)/src/bdd/cudd/cuddLinear.c \
	$(ABC)/src/bdd/cudd/cuddLiteral.c \
	$(ABC)/src/bdd/cudd/cuddMatMult.c \
	$(ABC)/src/bdd/cudd/cuddPriority.c \
	$(ABC)/src/bdd/cudd/cuddRead.c \
	$(ABC)/src/bdd/cudd/cuddRef.c \
	$(ABC)/src/bdd/cudd/cuddReorder.c \
	$(ABC)/src/bdd/cudd/cuddSat.c \
	$(ABC)/src/bdd/cudd/cuddSign.c \
	$(ABC)/src/bdd/cudd/cuddSolve.c \
	$(ABC)/src/bdd/cudd/cuddSplit.c \
	$(ABC)/src/bdd/cudd/cuddSubsetHB.c \
	$(ABC)/src/bdd/cudd/cuddSubsetSP.c \
	$(ABC)/src/bdd/cudd/cuddSymmetry.c \
	$(ABC)/src/bdd/cudd/cuddTable.c \
	$(ABC)/src/bdd/cudd/cuddUtil.c \
	$(ABC)/src/bdd/cudd/cuddWindow.c \
	$(ABC)/src/bdd/cudd/cuddZddCount.c \
	$(ABC)/src/bdd/cudd/cuddZddFuncs.c \
	$(ABC)/src/bdd/cudd/cuddZddGroup.c \
	$(ABC)/src/bdd/cudd/cuddZddIsop.c \
	$(ABC)/src/bdd/cudd/cuddZddLin.c \
	$(ABC)/src/bdd/cudd/cuddZddMisc.c \
	$(ABC)/src/bdd/cudd/cuddZddPort.c \
	$(ABC)/src/bdd/cudd/cuddZddReord.c \
	$(ABC)/src/bdd/cudd/cuddZddSetop.c \
	$(ABC)/src/bdd/cudd/cuddZddSymm.c \
	$(ABC)/src/bdd/cudd/cuddZddUtil.c 
