#!/bin/bash

# Go to root directory.
#
SKSAVE="$PWD"
cd "${0%/*}"
SKROOT="$PWD"

function quit {
  echo "failed, aborting process"
  cd "$SKSAVE"
  exit 1
}

# Build solver(s)
#
echo "Building solvers..."
# - build ABC
cd backend/abc60513
make clean && make libabc.a || quit
cd "$SKROOT"
# - build MiniSAT
cd backend/sat2005_submission/MiniSat_submission
make clean && make Solver.o || quit
cd "$SKROOT"
# - build Zchaff
cd backend/zchaff
g++ -O3 -c zchaff*.cpp || quit
cd "$SKROOT"
echo "...done"
# - build SBitII and copy executable
cd backend/SketchSolver/InputParser
[ -f rules.mak ] || ln -s rules-gcc.mak rules.mak
make clean && make || quit
for EXECFILE in SBitII{,.exe}; do
  [[ -x "$EXECFILE" && \
    ! -h "$SKROOT/frontend/sbin/$EXECFILE" ]] && \
    cp -f "$EXECFILE" "$SKROOT/frontend/sbin/"
done
cd "$SKROOT"
echo "...done"

# Build frontend.
#
echo "Building frontend..."
cd frontend
./build || quit
cd "$SKROOT"
echo "...done"

# Restore working directory.
#
cd "$SKSAVE"

