#!/bin/bash

# Go to root directory.
#
cd "${0%/*}"
SKROOT="$PWD"

function quit {
  echo "failed, aborting process"
  exit 1
}

# Build solver(s)
#
cd "$SKROOT/backend"
./build || quit

# Install SBit executable(s)
echo "installing sbit executable..."
cd "$SKROOT/backend/SketchSolver/InputParser"
for EXECFILE in SBitII{,.exe}; do
  [[ -x "$EXECFILE" && \
    ! -h "$SKROOT/frontend/sbin/$EXECFILE" ]] && \
    cp -f "$EXECFILE" "$SKROOT/frontend/sbin/" && \
    echo " $EXECFILE"
done
echo "...done"

# Build frontend.
#
cd "$SKROOT/frontend"
./build || quit
echo "...done"

