
//include "generators2.skh";
#define DEPTH 4


generator int expr(int x, int y, int z, int d){
	if (d==0){
		if (??){
			return x;
		}
		else if (??){
			return y;
		}
		else{
			return z;
		}
	}

	if (??){
		return x;
	}
	else if (??){
		return y;
	}
	else if (??){
		return z;
	}
	else{
		
		int e1 = expr(x,y,z,d-1);
		int e2 = expr(x,y,z,d-1);
		if (??){
			return e1+e2;
		}
		else{
			return e1*e2;
		}
	}
}

int exprFixed(int x, int y, int z){
	//int[3] operands = {x,y,z};
	//int[2] operations = {PLUS,TIMES};
	return expr(x,y,z,DEPTH);
}

harness void main(){
	
	//x*x + y*y*z + z*z*z;
	assert(exprFixed(1,1,2) == 11);
	assert(exprFixed(2,1,3) == 34);
	assert(exprFixed(1,2,4) == 81);

}