ABC_SRCS +=  $(ABC)/src/misc/espresso/cofactor.c \
	$(ABC)/src/misc/espresso/cols.c \
	$(ABC)/src/misc/espresso/compl.c \
	$(ABC)/src/misc/espresso/contain.c \
	$(ABC)/src/misc/espresso/cubehack.c \
	$(ABC)/src/misc/espresso/cubestr.c \
	$(ABC)/src/misc/espresso/cvrin.c \
	$(ABC)/src/misc/espresso/cvrm.c \
	$(ABC)/src/misc/espresso/cvrmisc.c \
	$(ABC)/src/misc/espresso/cvrout.c \
	$(ABC)/src/misc/espresso/dominate.c \
	$(ABC)/src/misc/espresso/equiv.c \
	$(ABC)/src/misc/espresso/espresso.c \
	$(ABC)/src/misc/espresso/essen.c \
	$(ABC)/src/misc/espresso/exact.c \
	$(ABC)/src/misc/espresso/expand.c \
	$(ABC)/src/misc/espresso/gasp.c \
	$(ABC)/src/misc/espresso/gimpel.c \
	$(ABC)/src/misc/espresso/globals.c \
	$(ABC)/src/misc/espresso/hack.c \
	$(ABC)/src/misc/espresso/indep.c \
	$(ABC)/src/misc/espresso/irred.c \
	$(ABC)/src/misc/espresso/map.c \
	$(ABC)/src/misc/espresso/matrix.c \
	$(ABC)/src/misc/espresso/mincov.c \
	$(ABC)/src/misc/espresso/opo.c \
	$(ABC)/src/misc/espresso/pair.c \
	$(ABC)/src/misc/espresso/part.c \
	$(ABC)/src/misc/espresso/primes.c \
	$(ABC)/src/misc/espresso/reduce.c \
	$(ABC)/src/misc/espresso/rows.c \
	$(ABC)/src/misc/espresso/set.c \
	$(ABC)/src/misc/espresso/setc.c \
	$(ABC)/src/misc/espresso/sharp.c \
	$(ABC)/src/misc/espresso/sminterf.c \
	$(ABC)/src/misc/espresso/solution.c \
	$(ABC)/src/misc/espresso/sparse.c \
	$(ABC)/src/misc/espresso/unate.c \
	$(ABC)/src/misc/espresso/verify.c
